use ecommerce_db;

-- 1. Orders per Month in 2018
SELECT 
    MONTHNAME(order_purchase_timestamp) AS month_name, 
    COUNT(order_id) AS total_orders
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY month_name
ORDER BY MIN(MONTH(order_purchase_timestamp));

-- 2. Average Number of Products per Order (Grouped by City)
SELECT 
    c.customer_city, 
    ROUND(COUNT(oi.product_id) / COUNT(DISTINCT oi.order_id), 2) AS avg_products_per_order
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_city
ORDER BY avg_products_per_order DESC
limit 10;

-- 3. Percentage of Total Revenue by Product Category
SELECT 
    p.product_category_name, 
    ROUND(
        SUM(oi.price) * 100.0 / SUM(SUM(oi.price)) OVER(), 
        1
    ) AS revenue_percentage
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY revenue_percentage DESC
LIMIT 10;

-- 4. Correlation Between Product Price and Purchase Count
SELECT 
	p.product_id,
    p.product_category_name,
    AVG(oi.price) AS mean_price, -- Matches 'price': 'mean'
    COUNT(oi.order_id) AS purchase_count -- Matches 'order_id': 'count'
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_category_name
ORDER BY purchase_count DESC
limit 10;

-- 5. Total Revenue Generated by Each Seller (Ranked)
SELECT 
    seller_id, 
    SUM(price) AS total_revenue,
    DENSE_RANK() OVER (ORDER BY SUM(price) DESC) AS seller_rank
FROM order_items
GROUP BY seller_id
limit 10;